/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FreeTrialForm = IDL.Record({
  'id' : IDL.Nat,
  'fullName' : IDL.Text,
  'preferredProgram' : IDL.Text,
  'email' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'submissionTime' : IDL.Int,
  'phone' : IDL.Text,
});
export const MembershipForm = IDL.Record({
  'id' : IDL.Nat,
  'preferredStartDate' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'submissionTime' : IDL.Int,
  'phone' : IDL.Text,
  'selectedPlan' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllFreeTrialForms' : IDL.Func([], [IDL.Vec(FreeTrialForm)], ['query']),
  'getAllMembershipForms' : IDL.Func([], [IDL.Vec(MembershipForm)], ['query']),
  'submitFreeTrialForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'submitMembershipForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FreeTrialForm = IDL.Record({
    'id' : IDL.Nat,
    'fullName' : IDL.Text,
    'preferredProgram' : IDL.Text,
    'email' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'submissionTime' : IDL.Int,
    'phone' : IDL.Text,
  });
  const MembershipForm = IDL.Record({
    'id' : IDL.Nat,
    'preferredStartDate' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'submissionTime' : IDL.Int,
    'phone' : IDL.Text,
    'selectedPlan' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllFreeTrialForms' : IDL.Func([], [IDL.Vec(FreeTrialForm)], ['query']),
    'getAllMembershipForms' : IDL.Func(
        [],
        [IDL.Vec(MembershipForm)],
        ['query'],
      ),
    'submitFreeTrialForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'submitMembershipForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };