/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FreeTrialForm {
    id: bigint;
    fullName: string;
    preferredProgram: string;
    email: string;
    preferredDateTime: string;
    notes?: string;
    submissionTime: bigint;
    phone: string;
}
export interface MembershipForm {
    id: bigint;
    preferredStartDate: string;
    fullName: string;
    email: string;
    message?: string;
    submissionTime: bigint;
    phone: string;
    selectedPlan: string;
}
export interface backendInterface {
    getAllFreeTrialForms(): Promise<Array<FreeTrialForm>>;
    getAllMembershipForms(): Promise<Array<MembershipForm>>;
    submitFreeTrialForm(fullName: string, phone: string, email: string, preferredDateTime: string, preferredProgram: string, notes: string | null): Promise<void>;
    submitMembershipForm(fullName: string, phone: string, email: string, selectedPlan: string, preferredStartDate: string, message: string | null): Promise<void>;
}
import type { FreeTrialForm as _FreeTrialForm, MembershipForm as _MembershipForm } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllFreeTrialForms(): Promise<Array<FreeTrialForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFreeTrialForms();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFreeTrialForms();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipForms(): Promise<Array<MembershipForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipForms();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipForms();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitFreeTrialForm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFreeTrialForm(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFreeTrialForm(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async submitMembershipForm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMembershipForm(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMembershipForm(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_FreeTrialForm_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FreeTrialForm): FreeTrialForm {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipForm_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipForm): MembershipForm {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fullName: string;
    preferredProgram: string;
    email: string;
    preferredDateTime: string;
    notes: [] | [string];
    submissionTime: bigint;
    phone: string;
}): {
    id: bigint;
    fullName: string;
    preferredProgram: string;
    email: string;
    preferredDateTime: string;
    notes?: string;
    submissionTime: bigint;
    phone: string;
} {
    return {
        id: value.id,
        fullName: value.fullName,
        preferredProgram: value.preferredProgram,
        email: value.email,
        preferredDateTime: value.preferredDateTime,
        notes: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.notes)),
        submissionTime: value.submissionTime,
        phone: value.phone
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    preferredStartDate: string;
    fullName: string;
    email: string;
    message: [] | [string];
    submissionTime: bigint;
    phone: string;
    selectedPlan: string;
}): {
    id: bigint;
    preferredStartDate: string;
    fullName: string;
    email: string;
    message?: string;
    submissionTime: bigint;
    phone: string;
    selectedPlan: string;
} {
    return {
        id: value.id,
        preferredStartDate: value.preferredStartDate,
        fullName: value.fullName,
        email: value.email,
        message: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.message)),
        submissionTime: value.submissionTime,
        phone: value.phone,
        selectedPlan: value.selectedPlan
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FreeTrialForm>): Array<FreeTrialForm> {
    return value.map((x)=>from_candid_FreeTrialForm_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MembershipForm>): Array<MembershipForm> {
    return value.map((x)=>from_candid_MembershipForm_n6(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
